
moneda = {
        "000": "OTRAS MONEDAS",
        "PES": "PESOS",
        "DOL": "Dólar ESTADOUNIDENSE",
        "002": "Dólar EEUU LIBRE",
        "003": "FRANCOS FRANCESES",
        "004": "LIRAS ITALIANAS",
        "005": "PESETAS",
        "006": "MARCOS ALEMANES",
        "007": "FLORINES HOLANDESES",
        "008": "FRANCOS BELGAS",
        "009": "FRANCOS SUIZOS",
        "010": "PESOS MEJICANOS",
        "011": "PESOS URUGUAYOS",
        "012": "REAL",
        "013": "ESCUDOS PORTUGUESES",
        "014": "CORONAS DANESAS",
        "015": "CORONAS NORUEGAS",
        "016": "CORONAS SUECAS",
        "017": "CHELINES AUTRIACOS",
        "018": "Dólar CANADIENSE",
        "019": "YENS",
        "021": "LIBRA ESTERLINA",
        "022": "MARCOS FINLANDESES",
        "023": "BOLIVAR (VENEZOLANO",
        "024": "CORONA CHECA",
        "025": "DINAR (YUGOSLAVO)",
        "026": "Dólar AUSTRALIANO",
        "027": "DRACMA (GRIEGO)",
        "028": "FLORIN (ANTILLAS HOLA",
        "029": "GUARANI",
        "030": "SHEKEL (ISRAEL)",
        "031": "PESO BOLIVIANO",
        "032": "PESO COLOMBIANO",
        "033": "PESO CHILENO",
        "034": "RAND (SUDAFRICANO",
        "035": "NUEVO SOL PERUANO",
        "036": "SUCRE (ECUATORIANO)",
        "040": "LEI RUMANOS",
        "041": "DERECHOS ESPECIALES DE GIRO",
        "042": "PESOS DOMINICANOS",
        "043": "BALBOAS PANAMEÑAS",
        "044": "CORDOBAS NICARAGÛENSES",
        "045": "DIRHAM MARROQUÍES",
        "046": "LIBRAS EGIPCIAS",
        "047": "RIYALS SAUDITAS",
        "048": "BRANCOS BELGAS FINANCIERA",
        "049": "GRAMOS DE ORO FINO",
        "050": "LIBRAS IRLANDESAS",
        "051": "Dólar DE HONG KONG",
        "052": "Dólar DE SINGAPUR",
        "053": "Dólar DE JAMAICA",
        "054": "Dólar DE TAIWAN",
        "055": "QUETZAL (GUATEMALTECOS)",
        "056": "FORINT (HUNGRIA)",
        "057": "BAHT (TAILANDIA)",
        "058": "ECU",
        "059": "DINAR KUWAITI",
        "060": "EURO",
        "061": "ZLTYS POLACOS",
        "062": "RUPIAS HINDÚES",
        "063": "LEMPIRAS HONDUREÑAS",
        "064": "YUAN (Rep. Pop. China",
}
